name: "Docker Test"

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call:
    inputs:
      event_name:
        type: string
        required: true
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  test:

    runs-on: ubuntu-latest
    environment: he
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:

      # debug
      - run: |
          echo "This job was triggered by this event: ${{ github.event_name }}"
          echo "This job is running on ${{ runner.os }}"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"
      
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      
      - name: Setup secrets file and run tests
        env:
          HE_USERNAME: ${{ secrets.HE_USERNAME }}
          HE_PASSWORD: ${{ secrets.HE_PASSWORD }}
          # must be a fqdn that is terminated with a dot (adding dot here) !!!
          TEST_ZONE_NAME: "${{ secrets.HE_TEST_ZONE_NAME }}."
        run: |
          sed "s/%%HE_USERNAME%%/${HE_USERNAME}/; s/%%HE_PASSWORD%%/${HE_PASSWORD}/" testdata/secret.yaml.example > testdata/he/secret.yaml
          make test

