name: "Helm test, build, push"

on:
  #  workflow_run:
  #    workflows: ["Docker test, build, push"]
  #    types:
  #      - completed
  workflow_call:
    inputs:
      github_ref:
        type: string
        required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  HELM_VERSION: 3.10.0
  CHART_DIR: deploy/cert-manager-webhook-he/
  CHART_NAME: cert-manager-webhook-he

jobs:
  helm-test:
    #if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:

      # debug
      - run: |
          #echo "This job was triggered by this event: ${{ github.event_name }}"
          echo "This job is running on ${{ runner.os }}"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}"

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: install helm
        uses: Azure/setup-helm@v4
        with:
          version: v${{ env.HELM_VERSION }}

      - name: Run helm lint
        run: helm lint $CHART_DIR

  helm-package-release:
    needs: helm-test
    if: inputs.event_name != 'pull_request'
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Get current tag
        #uses: actions-ecosystem/action-get-latest-tag@v1
        # latest can also be extracted using git client:
        # latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`
        id: get-tag
        env:
          thetag: ${{ inputs.github_ref }}
        run: |
          tag= "${$thetag#refs/*/}"
          echo "tag: $tag"
          echo "tag=${ tag }" >> "$GITHUB_OUTPUT"

      - name: Stripping v from version tag
        id: stripped-tag
        run: |
          tag= "${{ steps.get-tag.outputs.tag }}"
          version = "${$tag#v//)"
          echo "Version: ${version}"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      # could be replaced with an uglier sed command
      - name: Set image version in chart
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag = "${{ steps.stripped-tag.outputs.version }}"' "$CHART_DIR/values.yaml"

      # could be replaced with an uglier sed command
      - name: Update chart version in Chart.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{ steps.stripped-latest-tag.outputs.version }}"' "$CHART_DIR/Chart.yaml"

      - name: Log in to the Container registry
        if: github.ref_type != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create helm package
        run: helm package $CHART_DIR

      - name: Push helm package to OCI registry
        run: |
          helm push ${CHART_NAME}-${{ steps.bump-chart-semver.outputs.new_version }}.tgz oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts

